<?php

include CW_ROOT_UNIX."lib/fpdf/fpdf.php";

class cw_pdf extends FPDF {
  
  private $page_title="";
  private $header_font_size=8;
  private $auth; //
  private $custom_footer="";
  
  //auth object needed for identification of recipient of document
  function set_auth($auth){
    $this->auth=$auth;  
  }
  
  function set_custom_footer($footer){
    $this->custom_footer=$footer;
  }
  
  function set_page_title($title){
    $this->page_title=$title;
  }

  function set_header_font_size($n){
    $this->header_font_size=$n;
  }
  
  function Header(){
    $this->SetFont('Arial','B',$this->header_font_size);
    // Move to the right
    $this->setxy(80,3.5);
    $this->Cell(50,10,$this->page_title,0,0,'C');
    $this->Ln(12);
  }
    
  // Page footer
  function Footer(){
    //Have person_id/name?
    $name="";
    if (isset($this->auth)){
      $name=" for ".$this->auth->personal_records->get_name_first_last($this->auth->cuid);      
    }
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','',8);
    // Page number
    if ($this->custom_footer==""){
      $footer_text='Page '.$this->PageNo().'/{nb} - generated by ChurchWeb at '.CW_CHURCH_NAME.' on '.date("F j Y, g:ia",time()).$name;
    } else {
      $footer_text=$this->custom_footer;
    }
    $this->Cell(0,10,$footer_text,0,0,'C');
  }    
  
  function print_church_logo($scale=100,$x=0){
    if ($x==0){
      $x=$this->getx();
    }
    $this->setx($x);
    $cy=$this->gety();
    $scale=$scale/2;
    $width=200*($scale/100);
    $height=85*($scale/100);
    $this->Image(CW_ROOT_UNIX.CW_CHURCH_LOGO_FULL_WEBSIZE,$x,$cy,$width,$height);
    $this->sety($cy+$height+2);
  }

  function print_image($filename,$x=0){
    if ($x==0){
      $x=$this->getx();
    }
    $this->setx($x);
    $cy=$this->gety();
    $this->Image(CW_ROOT_UNIX.$filename,$x,$cy);
  }
  
  function print_header($string,$x_offset=0,$y_offset=0,$align="",$fontsize=16){
    $cx=$this->getx();
    $cy=$this->gety();
    $this->setxy($cx+$x_offset,$cy+$y_offset);
    // Arial italic 8
    $this->SetFont('Arial','',$fontsize);
    $this->cell(0,7,$string,0,0,$align);
    $this->setxy($cx,$cy);
  }
    
}

?>